# ----------------------------------------------------------------------------
# Copyright (c) 2005 Humanized, Inc. All rights reserved.
# ----------------------------------------------------------------------------
#
#   SConscript
#   Maintainer: Atul Varma
#
#   Python Version - 2.4
#
#   This is the PyCairo SConscript file.
#
# ----------------------------------------------------------------------------

# ----------------------------------------------------------------------------
# Imports
# ----------------------------------------------------------------------------

Import( "env" )

import glob


# ----------------------------------------------------------------------------
# Build Actions
# ----------------------------------------------------------------------------

sourceList = [
    glob.glob( "*.c" )
    ]

libs = [
    "${CAIRO_LIB_NAME}",
    ]

dllFile, expFile, libFile = env.SharedLibrary(
    target="${PYCAIRO_LIB_NAME}",
    source=sourceList,
    LIBS=libs
    )

env.Install( "${BASE_INSTALL_DIR}", dllFile )
