# ----------------------------------------------------------------------------
# Copyright (c) 2005 Humanized, Inc. All rights reserved.
# ----------------------------------------------------------------------------
#
#   SConscript
#   Maintainer: Atul Varma
#
#   Python Version - 2.4
#
#   This is the TransparentWindow SConscript file.
#
# ----------------------------------------------------------------------------

# ----------------------------------------------------------------------------
# Imports
# ----------------------------------------------------------------------------

Import( "env" )


# ----------------------------------------------------------------------------
# Build Actions
# ----------------------------------------------------------------------------

env = env.Copy()

libs = [
    "${PYCAIRO_LIB_NAME}",
    "${CAIRO_LIB_NAME}",
    "Gdi32.lib",
    "User32.lib",
    "CLogging",
    "AsyncEventProcessorRegistry",
    ]

pydFile, pyFile = env.buildSwigExtension(
    swigInterfaceFile = "TransparentWindow.i",
    source = "TransparentWindow.cxx",
    LIBS = libs,
    )

env.Install( "..", [pydFile, pyFile] )
