# ----------------------------------------------------------------------------
# Copyright (c) 2005 Humanized, Inc. All rights reserved.
# ----------------------------------------------------------------------------
#
#   SConscript
#   Maintainer: Atul Varma
#
#   Python Version - 2.4
#
#   This is the FreeType2 SConscript file.
#
# ----------------------------------------------------------------------------

# ----------------------------------------------------------------------------
# Imports
# ----------------------------------------------------------------------------

Import( "env" )


# ----------------------------------------------------------------------------
# Build Actions
# ----------------------------------------------------------------------------

env = env.Copy()

cppDefines = {
    "HUMANIZED_FT2_USE_DL_EXPORT" : "1",
    }

# We're not using a glob.glob() here; this list of files was
# constructed from looking at the "docs/INSTALL.ANY" file from the
# original FreeType distribution.
sourceList = [
    "src/base/ftsystem.c",
    "src/base/ftinit.c",
    "src/base/ftdebug.c",
    "src/base/ftbase.c",
    "src/base/ftbitmap.c",
    "src/base/ftglyph.c",
    "src/base/ftbbox.c",
    "src/base/ftmm.c",
    "src/autofit/autofit.c",      # auto-hinting module
    "src/sfnt/sfnt.c",            # SFNT files support
                                  # (required for TrueType)
    "src/psnames/psnames.c",      # PostScript glyph names support
                                  # (required for TrueType)
    "src/truetype/truetype.c",    # TrueType font driver
    "src/smooth/smooth.c",        # Anti-aliasing rasterizer
    ]

env.Append(
    CPPDEFINES = cppDefines
    )

libFiles = env.SharedLibrary(
    target = "${FT2_LIB_NAME}",
    source = sourceList,
    )

env.Install( "${BASE_INSTALL_DIR}", libFiles[0] )
